apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gwtest-deployment
  labels:
    app: api-gwtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gwtest
  template:
    metadata:
      labels:
        app: api-gwtest
    spec:
      containers:
        - name: api-container
          # REEMPLAZA ESTA URL POR TU URL DE ECR
          image: 607628833711.dkr.ecr.us-east-1.amazonaws.com/api-gwtest:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gwtest-service
spec:
  type: LoadBalancer
  selector:
    app: api-gwtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080